#!/bin/sh

touch /etc/config/applications

# Make sure avahi-client is running. If not, start it.
if [ -z `pgrep avahi-client` ]; then
	avahi-client &
	sleep 2
fi

# Send signal to avahi-client so it will dump cache to /tmp/avahi-client.out 
kill -s USR1 `pgrep avahi-client`
sleep 2

while read service; do
	#parse $service
	#format:
	#	<interface>;<protocol>;<hostname long>;<type>;<domain>;<hostname.domain>;<ip addr>;<port>;<txt record>
	#	     1     ;    2     ;        3      ;   4  ;   5    ;        6        ;    7    ;  8   ;      9

	# Service advertisements must have txt records
	txt=`echo $service | cut -d ';' -f9-`
	if [ -z "$txt" ]; then
		continue
	fi

	# get fingerprint/signature of service, compare to map of existing apps -> if fingerprint found, but sig different, update app
	fingerprint=`echo $txt |grep -o fingerprint=[^\"]* |cut -c13- |sed -e s/"&"/"\&amp\;"/g |sed -e s/"<"/"\&lt;"/g |sed -e s/">"/"\&gt;"/g`
	signature=`echo $txt |grep -o signature=[^\"]* |cut -c11- |sed -e s/"&"/"\&amp\;"/g |sed -e s/"<"/"\&lt;"/g |sed -e s/">"/"\&gt;"/g`

	if [ -z $fingerprint ]; then
		continue
	fi

	match=''
	apps=`cat /etc/config/applications |grep "^config application " |cut -c21- |sed -e s/\'$//`
	for app in $apps; do
		if [ $app == $fingerprint ]; then
			if [ `uci get applications.$app.signature` == $signature ]; then
				match=true
			fi
		fi
	done
	if [ $match ]; then
		continue
	fi

	# Gather service information
	APPNAME=`echo $txt |grep -o application=[^\"]* |cut -c13- |sed -e s/"&"/"\&amp\;"/g |sed -e s/"<"/"\&lt;"/g |sed -e s/">"/"\&gt;"/g`
	UUID="$fingerprint"
	protocol=`echo $service |awk -F ';' '{print $2}' |sed -e s/"&"/"\&amp\;"/g |sed -e s/"<"/"\&lt;"/g |sed -e s/">"/"\&gt;"/g`
	transport=`echo $service |awk -F ';' '{print $4}' |grep -o "[^_]*$" |sed -e s/"&"/"\&amp\;"/g |sed -e s/"<"/"\&lt;"/g |sed -e s/">"/"\&gt;"/g`
	full_type=`echo $service |awk -F ';' '{print $4}'`
	domain=`echo $service |awk -F ';' '{print $5}'`
	nick=`echo $txt |grep -o nick=[^\"]* |cut -c6- |sed -e s/"&"/"\&amp\;"/g |sed -e s/"<"/"\&lt;"/g |sed -e s/">"/"\&gt;"/g`
	ttl=`echo $txt |grep -o ttl=[^\"]* |cut -c5-`
	# ipaddr=`echo $service | awk -F ';' '{print $7}' |sed -e s/"<"/"%3C"/g |sed -e s/">"/"%3E"/g |sed -e s/"[[:space:]]"/"%20"/g`
	ipaddr=`echo $txt |grep -o ipaddr=[^\"]* |cut -c8- |sed -e s/"<"/"%3C"/g |sed -e s/">"/"%3E"/g |sed -e s/"[[:space:]]"/"%20"/g`
	port=`echo $service | awk -F ';' '{print $8}'`
	service_uuid=`echo $txt |grep -o uuid=[^\"]* |cut -c6- |sed -e s/"&"/"\&amp\;"/g |sed -e s/"<"/"\&lt;"/g |sed -e s/">"/"\&gt;"/g`
	icon=`echo $txt |grep -o icon=[^\"]* |cut -c6- |sed -e s/"<"/"%3C"/g |sed -e s/">"/"%3E"/g |sed -e s/"[[:space:]]"/"%20"/g`
	description=`echo $txt |grep -o description=[^\"]* |cut -c13- |sed -e s/"&"/"\&amp\;"/g |sed -e s/"<"/"\&lt;"/g |sed -e s/">"/"\&gt;"/g`
	types=`echo $txt |grep -o type=[^\"]* |cut -c6- |sed 's/ /%#%#%#%#%/g' |sed -e s/"&"/"\&amp\;"/g |sed -e s/"<"/"\&lt;"/g |sed -e s/">"/"\&gt;"/g`

	##################### INPUT VALIDATION/SANITIZING ##########################
	# HTML ENCODING: sed -e s/"&"/"\&amp\;"/g |sed -e s/"<"/"\&lt;"/g |sed -e s/">"/"\&gt;"/g
	# URL ENCODING: sed -e s/"<"/"%3C"/g |sed -e s/">"/"%3E"/g |sed -e s/"[[:space:]]"/"%20"/g
	# is_uint: grep -E "^[[:digit:]]+$"
	# is_port: if [ $? -eq 0 -a $test -ge 0 -a $test -le 65535 ]
	# uci_encode: awk 'BEGIN{FS="";for(n=0;n<256;n++)ord[sprintf("%c",n)]=n}{for(i=1;i<=NF;i++)if(match($i,/[a-zA-Z0-9]/)){printf $i} else {printf "_"ord[$i]}}'
	echo "$ttl" |grep -E "^[[:digit:]]+$"
	if [ $? -ne 0 ]; then
		continue
	fi
	
	echo "$port" |grep -E "^[[:digit:]]+$"
	if [ $? -ne 0 -o $port -lt 0 -o $port -gt 65535 ]; then
		continue
	fi
	
	##################### VERIFY SIGNATURE ##########################
	app_types=''
	for type in $types; do
		type=`echo -n $type |sed -e 's/%#%#%#%#%/ /g'`
		app_types="$app_types<txt-record>type=$type</txt-record>"
	done
	sig_tmpl="<type>$full_type</type>
<domain-name>$domain</domain-name>
<port>$port</port>
<txt-record>application=$APPNAME</txt-record>
<txt-record>nick=$nick</txt-record>
<txt-record>ttl=$ttl</txt-record>
<txt-record>ipaddr=$ipaddr</txt-record>
$app_types
<txt-record>icon=$icon</txt-record>
<txt-record>description=$description</txt-record>"
	echo "$sig_tmpl" |serval-verify -s $signature -i $fingerprint
	if [ `echo $?` != '0' ]; then
		echo -e "service failed verification\n"
		echo -e "[$sig_tmpl]\n"
		continue
	fi

	# Submit service information to UCI
	uci set applications.$UUID=application
	uci set applications.$UUID.name="$APPNAME"
	uci set applications.$UUID.protocol="$protocol"
	uci set applications.$UUID.transport="$transport"
	uci set applications.$UUID.nick="$nick"
	if [ -n $ttl ]; then
		uci set applications.$UUID.ttl="$ttl"
	fi
	uci set applications.$UUID.ipaddr="$ipaddr"
	if [ -n $port ]; then
		uci set applications.$UUID.port="$port"
	fi
	uci set applications.$UUID.uuid="$service_uuid"
	uci set applications.$UUID.fingerprint="$fingerprint"
        uci set applications.$UUID.signature="$signature"
	uci set applications.$UUID.icon="$icon"
	uci set applications.$UUID.description="$description"

	# Adding service types with whitespace in them takes some extra work
	uci delete applications.$UUID.type
	uci set applications.$UUID.type="COMMOTION TYPE LIST PLACEHOLDER"
	uci commit applications
	typeList=""
	for type in $types; do
		type=`echo -n $type |sed -e 's/%#%#%#%#%/ /g'`
		typeList="$typeList\n\tlist type '$type'"
	done
	typeList=`echo "$typeList" |cut -c3-`
	sed -i -e "s/\toption type 'COMMOTION TYPE LIST PLACEHOLDER'/$typeList/" /etc/config/applications

done < "/tmp/avahi-client.out"

exit